# Generated by Django 6.0.1 on 2026-01-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom unique de la catégorie', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description de la tâche')),
                ('is_completed', models.BooleanField(default=False, help_text='Indique si la tâche est terminée')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la tâche')),
                ('category', models.ForeignKey(help_text='Catégorie associée à la tâche', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.category')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-created_at'],
            },
        ),
    ]
